### ISSUE TITLE
Specify date range?

### ISSUE THREAD

**Issue by LRonHubs** [HakimMliki/my-google-news#1]
Are there any endpoints for specifying a specific date range? E.g. December 15th 2016 - December 16th 2016

**Comment by HakimMliki** [comment]
var myGoogleNews = require('my-google-news');

// assign one of the values below. Nothing is set by default. 
myGoogleNews.timeSpan = 'h' // information indexed in the past hour 
myGoogleNews.timeSpan = 'd' // information indexed in the past day 
myGoogleNews.timeSpan = 'w' // information indexed in the past week 
myGoogleNews.timeSpan = 'm' // information indexed in the past month 
myGoogleNews.timeSpan = 'y' // information indexed in the past year
